version: '3'
services:

  ui:
    container_name: ui
    build: ./ui
    ports:
      - "${UI_PORT}:${UI_PORT}"
    depends_on:
      - api-gateway
    stdin_open: true
    networks:
      - itaNet
    volumes:
      - ./ui:/usr/src/app

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - '${API_GATEWAY_PORT}:${API_GATEWAY_PORT}'
    depends_on:
      - db
    networks:
      - itaNet
    volumes:
      - ./api-gateway:/usr/src/app
  db:
    container_name: db
    build: ./db
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - itaNet
    volumes:
      - ./db:/usr/src/app

  session:
    container_name: session
    build: ./session
    ports:
      - '${SESSION_PORT}:${SESSION_PORT}'
    depends_on:
      - db
    networks:
      - itaNet
    volumes:
      - ./session:/usr/src/app
  test:
    container_name: test
    build: ./test
    ports:
      - '${TEST_PORT}:${TEST_PORT}'
    depends_on:
      - db
    networks:
      - itaNet
    volumes:
      - ./test:/usr/src/app



networks:
  itaNet:
    driver: bridge
    ipam:
      driver: default
